### ISSUE TITLE
Set a time interval for each location request

### ISSUE THREAD

**Issue by emersiljr** [shernandezp/XamarinForms.LocationService#9] opened 2021-07-02 23:20 UTC
I realize that the location service has a random time, how and where could a time interval be configured to request location? For example, every 10 or 20 seconds? I couldn't find where this configuration would be.

**Comment by shernandezp** [comment] 2021-07-02 23:39
This is not a bug. I'm closing it. Updates of the location are fixed, not random. If you want to use this code for another project, I suggest you go through it, debug it, and you will find where the interval is set.

**Closed as completed by shernandezp** 2021-07-02 23:39 UTC
